title: Configuring Educates Lookup Service
slug: lab-lookup-configuration
description: How to configure Educates Lookup Service as API Frontend to multiple Educates Clusters.
author: Educates Team
image: educates
repository:
  org: educates
  name: labs-installation-guides
  ref: "1.0.0"
  path: workshops/lab-lookup-configuration/resources/workshop.yaml
install_url: https://github.com/educates/labs-installation-guides/releases/download/1.0.0/lab-lookup-configuration.yaml
labels:
  - educates-showcase
  - configuration
  - educates-lookup-service