title: Using Java Environment in Educates
slug: lab-java-environment
description: How to use Java Environment in Educates.
author: Educates Team
image: educates_java
repository:
  org: educates
  name: labs-educates-showcase
  ref: "1.0.0"
  path: workshops/lab-java-environment/resources/workshop.yaml
install_url: https://github.com/educates/labs-educates-showcase/releases/download/1.0.0/lab-java-environment.yaml
labels:
  - educates-showcase
  - java
  - educates-language-environment
