title: Using Conda Environment in Educates
slug: lab-conda-environment
description: How to use Conda Environment in Educates.
author: Educates Team
image: educates_python
repository:
  org: educates
  name: labs-educates-showcase
  ref: "1.0.0"
  path: workshops/lab-conda-environment/resources/workshop.yaml
install_url: https://github.com/educates/labs-educates-showcase/releases/download/1.0.0/lab-conda-environment.yaml
labels:
  - educates-showcase
  - educates-language-environment
  - conda
