apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-git-repositories
spec:
  description: Overview of using local hosted Git repositories.
  duration: 30m
  session:
    applications:
      files:
        enabled: true
      git:
        enabled: true
      terminal:
        enabled: true
        layout: split
    namespaces:
      budget: medium
  title: Git Repositories
  version: 1.0.0
  workshop:
    files:
    - image:
        url: ghcr.io/educates/labs-educates-showcase/lab-git-repositories-files:1.0.0
      includePaths:
      - /resources/**
      - /workshop/**
