apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-integrated-editor
spec:
  description: Overview of integrated VS Code editor.
  duration: 30m
  session:
    applications:
      editor:
        enabled: true
      files:
        enabled: true
      terminal:
        enabled: true
        layout: split
    namespaces:
      budget: medium
  title: Integrated Editor
  version: 1.0.0
  workshop:
    files:
    - image:
        url: ghcr.io/educates/labs-educates-showcase/lab-integrated-editor-files:1.0.0
      includePaths:
      - /resources/**
      - /workshop/**
